# Generated by Django 2.2.4 on 2021-03-13 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fecha_cumpleaños',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
