# Generated by Django 2.2.4 on 2021-03-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_user_fecha_cumpleaños'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fecha_cumpleaños',
            field=models.DateField(),
        ),
    ]
