# Generated by Django 2.2.4 on 2021-03-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20210313_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fecha_cumpleaños',
            field=models.DateTimeField(),
        ),
    ]
